# Copyright 2026 Bing Xie
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable, Sequence

class PendingTree:
    def __init__(self) -> None: ...
    def insert(self, rid: int, tokens: Sequence[int]) -> None: ...
    def insert_many(self, items: Sequence[tuple[int, Sequence[int]]]) -> None: ...
    def remove(self, rid: int) -> None: ...
    def remove_many(self, rids: Sequence[int]) -> int: ...
    def discard(self, rid: int) -> bool: ...
    def longest_shared_prefix(self, rid: int) -> int: ...
    def match_prefix(self, tokens: Sequence[int]) -> int: ...
    def node_count(self) -> int: ...
    def has_sharing(self) -> bool: ...
    def shared_rid_count(self) -> int: ...
    def singleton_rid_count(self) -> int: ...
    def compute_req_scores(self) -> dict[int, int]: ...
    def cluster_info(self, rid: int) -> tuple[int, int, int] | None: ...
    def all_cluster_info(self) -> dict[int, tuple[int, int, int] | None]: ...
    def lpm_order(
        self,
        reqs: Sequence[tuple[int, int]],
        check_threshold: int = ...,
        deprioritize_threshold: int = ...,
    ) -> list[int]: ...
    def tokens(self, rid: int) -> list[int] | None: ...
    def pending_demand(self, path: Sequence[int]) -> int: ...
    def terminators_at(self, path: Sequence[int]) -> int: ...
    def longest_match_along(
        self, tokens: Sequence[int]
    ) -> tuple[int, int | None]: ...
    def record_decode(self, tokens: Sequence[int], output_len: int) -> None: ...
    def predict_decode(
        self, tokens: Sequence[int], min_samples: int = 3
    ) -> tuple[float, int] | None: ...
    def snapshot_for_walk(
        self,
    ) -> list[tuple[int, int, list[int], list[int], int]]: ...
    def compute_main_hits(
        self,
        cache_match_fn: Callable[[list[int]], int],
        min_pending_count: int = 1,
    ) -> dict[int, int]: ...
    def __contains__(self, rid: int) -> bool: ...
    def __len__(self) -> int: ...

def lpm_sort_order(keys: Sequence[tuple[int, bool]]) -> list[int]: ...
def peek_clpm_sort_order(
    keys: Sequence[tuple[int, int, int, int, int, int]],
) -> list[int]: ...
