# Copyright 2026 Anonymous Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Sequence

class PendingTree:
    def __init__(self) -> None: ...
    def insert(self, rid: int, tokens: Sequence[int]) -> None: ...
    def remove(self, rid: int) -> None: ...
    def discard(self, rid: int) -> bool: ...
    def longest_shared_prefix(self, rid: int) -> int: ...
    def match_prefix(self, tokens: Sequence[int]) -> int: ...
    def node_count(self) -> int: ...
    def cluster_info(self, rid: int) -> tuple[int, int, int] | None: ...
    def all_cluster_info(self) -> dict[int, tuple[int, int, int] | None]: ...
    def rank(
        self,
        main_hits: dict[int, int],
        total_tokens: dict[int, int],
        wait_counts: dict[int, int],
        unlock_weight: float,
        redundancy_weight: float,
        wait_weight: float,
    ) -> list[int]: ...
    def tokens(self, rid: int) -> list[int] | None: ...
    def pending_demand(self, path: list[int]) -> int: ...
    def terminators_at(self, path: list[int]) -> int: ...
    def compute_main_hits(self, cache_match_fn) -> dict[int, int]: ...
    def __contains__(self, rid: int) -> bool: ...
    def __len__(self) -> int: ...
